services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  mail:
      build: ./mail
      container_name: mail
      ports:
        - "${MAIL_PORT}:${MAIL_PORT}"
      env_file:
        - .env

  backend-dotnet-img:
    build: ../backend-dotnet
    container_name: backend-dotnet-container
    ports:
      - "${BACKEND_DOTNET_PORT}:${BACKEND_DOTNET_PORT}"
    env_file:
      - .env
    depends_on:
      # - postgres
      - redis
      - mail

  frontend-vue-img:
    build: ../frontend-vue
    container_name: frontend-vue-container
    ports:
      - "${VITE_FRONTEND_PORT}:${VITE_FRONTEND_PORT}"
    env_file:
      - .env
    depends_on:
      - backend-dotnet-img
   
  llama:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-container
    ports:
      - "${LLAMA_PORT}:${LLAMA_PORT}"
    env_file:
      - .env
    volumes:
      - "${LLAMA_MODEL_VOLUME_PATH}:/models"
    command: >
      -m /models/${LLAMA_MODEL_NAME}
      --host 0.0.0.0
      --port ${LLAMA_PORT}

  piper:
    image: ${PIPER_IMAGE}
    container_name: ${PIPER_CONTAINER}
    command: >
      --voice ${PIPER_VOICE}
    volumes:
      - ${PIPER_DATA}:/data
    ports:
      - "${PIPER_PORT}:${PIPER_PORT}"

  piper-gateway:
    image: ${GATEWAY_IMAGE}
    container_name: ${GATEWAY_CONTAINER}
    working_dir: /app
    volumes:
      - ${GATEWAY_APP_PATH}:/app
    command: >
      bash -c "pip install fastapi uvicorn wyoming redis &&
      uvicorn server:app --host ${GATEWAY_HOST} --port ${GATEWAY_INTERNAL_PORT}"
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_INTERNAL_PORT}"

  parser:
    build: ./parser
    container_name: parser-container
    env_file:
      - .env
    ports:
      - "${PARSER_PORT}:${PARSER_PORT}"
    restart: unless-stopped

  filestorage:
    build: ./filestorage
    container_name: filestorage-container
    ports:
      - "${FILESTORAGE_PORT}:3007"
    environment:
      - FILESTORAGE_API_KEY=${FILESTORAGE_API_KEY}
      - UPLOAD_DIR=/data/files
    volumes:
      - filestorage_data:/data/files
    restart: unless-stopped

volumes:
  redis_data:
  filestorage_data: